@startuml
state "Initialisation" ad Init
state "Read sensors" as ReadSensors
state "Update position" as UpdatePosition
state c <<choice>>
state d <<choice>>
state "Update waypoint" as UpdateWaypoint

[*] --> Init
Init --> ReadSensors
ReadSensors --> UpdatePosition
UpdatePosition --> c
c --> Move : Not arrived to goal
c --> UpdateWaypoint : Arrived to goal
UpdateWaypoint --> d
d --> [*] : No more waypoints
d --> Move : Still more waypoints
Move --> ReadSensors

Init : Load configuration file
Init : Setup sensors and actuators
Init : Read mission waypoints
Init : Set first waypoint as goal
ReadSensors : Reads all sensor data

@enduml
